version: '2'
services:
    mongo:
        image: mongo:3.0.10
    regexrace:
        build: .
        ports:
            - "80:8080"
        volumes:
            - .:/go/src/github.com/thylong/regexrace
        links:
            - mongo
